### ISSUE TITLE
How to get the Jacobian matrix for least square inversion?

### ISSUE THREAD

**Issue by xichaoqiang** [keurfonluu/fteikpy#5]
How can I get the Jacobian matrix from the existing code?

**Comment by xichaoqiang** [comment]
![图片](https://user-images.githubusercontent.com/30900789/105118999-63f91180-5b0a-11eb-8b99-89cfcfbc6927.png)

For tomography inversion problem.How can I get the G matrix （the frechet derivative matrix/ Jacobian matrix） ?

**Comment by keurfonluu** [comment]
Basically, I think that you need to determine for each data point (traveltime between every source-receiver couples) whether the ray that links the source to the receiver traverses each element of your grid. If yes, *Gjk* is the product of the slowness at that grid element and the time the ray spends in it. Otherwise, it's zero. Note that the matrix **G** is sparse (lot of zeros) and model dependent.

I don't think the method `raytrace` is suitable for that problem since the step size is constant. You might have to retrace the path from source to receiver using the traveltime gradient grid. You can look at the source code of `raytrace`, though.

**Comment by xichaoqiang** [comment]
Thanks for your reply.I will see it.

**Comment by keurfonluu** [comment]
Closing this issue in favor of issue #7.
